### ISSUE TITLE
How to run Intellidroid with Gator?

### ISSUE THREAD

**Issue by yufeiyang1995** [zhuowei/IntelliDroidUiEvaluationCode#1]
I read the SettingUpIntellidroid.md and I find that you setup IntelliDroid with Gator. I thought the Gator is a static analysis tool，but you still use WALA to analysis apps staticly. So,I am confused how to run Intellidroid with Gator.

Look forward to your reply, thank u!

**Comment by zhuowei** [comment]
@yufeiyang1995 This was for a prototype of IntelliDroid that attempted to improve GUI analysis. (It didn't work very well.)

This prototype runs Gator separately during the preprocessing step, and dumps the view information to an .xml file. The modified version of IntelliDroid then reads Gator's output during analysis.

I hoped that Gator's UI analysis would supplement IntelliDroid's own GUI analysis, but in testing it didn't produce much of a benefit.

If you really want to try it, checkout [the feature/gui branch](https://github.com/zhuowei/IntelliDroid/tree/feature/gui), download gator-3.4, and extract it to `AppAnalysis/preprocess/gator-3.4`.

If you're working on GUI support for IntelliDroid, you should discuss your approach with @miwong, the primary author of IntelliDroid. My attempt, which wasn't very successful, is probably not a good starting point.

**Comment by yufeiyang1995** [comment]
Thank you very much～
